title = "Orchestra"

[footer]
style = "dark"
copyright = "Built with ❤️ "

[[classOrder]]
section = "Base Members"
collapsed = false
tag = "Base"

[[classOrder]]
section = "Effects"
collapsed = true
tag = "Effects"

[[classOrder]]
section = "Output"
collapsed = true
tag = "Output"

[[classOrder]]
section = "Stream"
collapsed = true
tag = "Stream"

[[classOrder]]
section = "Transforms"
collapsed = true
tag = "Transforms"